export interface PublicPageDefinition {
  path: string;
  label: string;
  group: string;
}

export const PUBLIC_PAGES: PublicPageDefinition[] = [
  { path: "/choose-location", label: "Choose Location", group: "Core" },
  { path: "/salt-lake-city", label: "Salt Lake City Home", group: "Locations" },
  { path: "/wilmington-nc", label: "Wilmington NC Home", group: "Locations" },
  { path: "/myrtle-beach-sc", label: "Myrtle Beach SC Home", group: "Locations" },
  { path: "/myrtle-beach-sc/list-your-vehicle", label: "Myrtle Beach List Your Vehicle", group: "Locations" },
  { path: "/charleston-sc", label: "Charleston SC Home", group: "Locations" },
  { path: "/charleston-sc/list-your-vehicle", label: "Charleston List Your Vehicle", group: "Locations" },
  { path: "/fleet", label: "Fleet", group: "Fleet" },
  { path: "/salt-lake-city/fleet", label: "Salt Lake City Fleet", group: "Fleet" },
  { path: "/wilmington-nc/fleet", label: "Wilmington NC Fleet", group: "Fleet" },
  { path: "/myrtle-beach-sc/fleet", label: "Myrtle Beach SC Fleet", group: "Fleet" },
  { path: "/charleston-sc/fleet", label: "Charleston SC Fleet", group: "Fleet" },
  { path: "/salt-lake-city/pick-up-and-drop-off", label: "SLC Pick Up and Drop Off", group: "SLC" },
  { path: "/salt-lake-city/detail-shop/book", label: "SLC Detail Shop Booking", group: "SLC" },
  { path: "/salt-lake-city/detail-shop", label: "SLC Detail Shop", group: "SLC" },
  { path: "/salt-lake-city/chauffeur-services", label: "SLC Chauffeur Services", group: "SLC" },
  { path: "/salt-lake-city/deals", label: "SLC Deals", group: "SLC" },
  { path: "/salt-lake-city/jobs/apply", label: "SLC Job Application", group: "SLC" },
  { path: "/salt-lake-city/jobs", label: "SLC Jobs", group: "SLC" },
  { path: "/salt-lake-city/suggested-cars", label: "SLC Suggested Cars", group: "SLC" },
  { path: "/salt-lake-city/testimonials", label: "SLC Testimonials", group: "SLC" },
  { path: "/salt-lake-city/reviews-options", label: "SLC Review Options", group: "SLC" },
  { path: "/salt-lake-city/reviews", label: "SLC Reviews", group: "SLC" },
  { path: "/salt-lake-city/extras", label: "SLC Extras", group: "SLC" },
  { path: "/salt-lake-city/privacy-policy", label: "SLC Privacy Policy", group: "SLC" },
  { path: "/salt-lake-city/terms-and-conditions", label: "SLC Terms and Conditions", group: "SLC" },
  { path: "/salt-lake-city/terms", label: "SLC Terms", group: "SLC" },
  { path: "/salt-lake-city/onboarding", label: "SLC Onboarding", group: "SLC" },
  { path: "/salt-lake-city/contact", label: "SLC Contact", group: "SLC" },
  { path: "/wilmington-nc/testimonials", label: "Wilmington Testimonials", group: "Wilmington" },
  { path: "/wilmington-nc/reviews-options", label: "Wilmington Review Options", group: "Wilmington" },
  { path: "/wilmington-nc/reviews", label: "Wilmington Reviews", group: "Wilmington" },
  { path: "/wilmington-nc/extras", label: "Wilmington Extras", group: "Wilmington" },
  { path: "/wilmington-nc/privacy-policy", label: "Wilmington Privacy Policy", group: "Wilmington" },
  { path: "/wilmington-nc/terms-and-conditions", label: "Wilmington Terms and Conditions", group: "Wilmington" },
  { path: "/wilmington-nc/terms", label: "Wilmington Terms", group: "Wilmington" },
  { path: "/wilmington-nc/onboarding", label: "Wilmington Onboarding", group: "Wilmington" },
  { path: "/wilmington-nc/contact", label: "Wilmington Contact", group: "Wilmington" },
  { path: "/detail-shop/book", label: "Detail Shop Booking", group: "Legacy Public" },
  { path: "/detail-shop", label: "Detail Shop", group: "Legacy Public" },
  { path: "/chauffeur-services", label: "Chauffeur Services", group: "Legacy Public" },
  { path: "/pick-up-and-drop-off", label: "Pick Up and Drop Off", group: "Legacy Public" },
  { path: "/deals", label: "Deals", group: "Legacy Public" },
  { path: "/jobs/apply", label: "Job Application", group: "Legacy Public" },
  { path: "/jobs", label: "Jobs", group: "Legacy Public" },
  { path: "/privacy-policy", label: "Privacy Policy", group: "Legacy Public" },
  { path: "/terms-and-conditions", label: "Terms and Conditions", group: "Legacy Public" },
  { path: "/terms", label: "Terms", group: "Legacy Public" },
  { path: "/testimonials", label: "Testimonials", group: "Legacy Public" },
  { path: "/reviews-options", label: "Review Options", group: "Legacy Public" },
  { path: "/reviews", label: "Reviews", group: "Legacy Public" },
  { path: "/extras", label: "Extras", group: "Legacy Public" },
  { path: "/suggested-cars", label: "Suggested Cars", group: "Legacy Public" },
  { path: "/onboarding", label: "Onboarding", group: "Legacy Public" },
  { path: "/contact", label: "Contact", group: "Legacy Public" },
  { path: "/employee-form", label: "Employee Form", group: "Forms" },
  { path: "/co-host-form", label: "Co-Host Form", group: "Forms" },
];

export function publicPageLabel(path: string): string {
  return PUBLIC_PAGES.find((page) => page.path === path)?.label || path;
}
